### ISSUE TITLE
Giving module not found error

### ISSUE THREAD

**Issue by ghost** [FireHead90544/gogoanime-dl#1]
I am attaching an image below, 
![image](https://user-images.githubusercontent.com/59922023/169757483-8c6c44b5-b5c6-4b2f-8fc3-ebdf23661aa4.png)

**Comment by FireHead90544** [comment]
Hello There,
The error shows that you don't have the required module 'gogoanimeapi' installed.

You need to run the `pip install gogoanimeapi` cell or just run this in a separate cell before executing the main cell.


**Though I can't guarantee if this would work now since gogoanime updated the way they fetch the videos from their servers.**

I am working on another version which would work perfectly, but as I am having my examinations these days, I have postponed it's development and release. I'll try to complete it asap :)

Until then, check out `anime-dl` :D

**Comment by FireHead90544** [comment]
I re-coded it from scratch and made it a better CLI application: https://github.com/FireHead90544/SenPY
